Repository COS301-SE-2024/Crop-Prediction-System, pull requests merged in 2024-08, with the labels that each got.

#168 Backend Unit Testing
  .coverage
  .github/workflows/backend_unit.yml
  README.md
  backend/database/supabaseFunctions.py
  backend/logic/calculateHectare.py
  backend/model/model.py
  backend/test/test_calculateHectare.py
  backend/test/test_functions.py
  backend/test/test_gemini.py
  backend/test/test_model.py
  backend/test/test_supabaseFunctions.py
  backend/test/test_weather.py
  frontend/components/FieldData.vue
  frontend/components/GoogleMap.vue
  frontend/components/LogsView.vue
  frontend/cypress.config.ts
  frontend/cypress/e2e/dashboard.cy.ts
  frontend/cypress/e2e/login.cy.ts
  frontend/cypress/e2e/signup..cy.ts
  frontend/cypress/e2e/spec.cy.ts
  frontend/cypress/fixtures/example.json
  frontend/cypress/support/commands.ts
  frontend/cypress/support/e2e.ts
  frontend/cypress/support/index.d.ts
  frontend/pages/Login/index.vue
  frontend/pages/Signup/index.vue
  frontend/pages/index.vue
  frontend/pages/inputs/add-field-data/index.vue
  frontend/pages/inputs/manage-fields/index.vue
  frontend/tests/integration/GetFields.spec.ts
  frontend/tests/integration/ShowMap.spec.ts
  frontend/tests/unit/CustomLegend.spec.ts
  frontend/tests/unit/FieldCard.spec.ts
  frontend/tests/unit/FieldData.spec.ts
  frontend/tests/unit/GoogleMap.spec.ts
  frontend/tests/unit/GoogleMapsField.spec.ts
  frontend/tests/unit/LogsToolbar.spec.ts
  frontend/tests/unit/Navbar.spec.ts
  frontend/tests/unit/StatsCard.spec.ts
Labels: testing

#169 Removed unused component that may cause issues
  frontend/components/LogsView.vue
  frontend/server/api/getTeamFieldData.ts
  frontend/server/api/getTeamFields.ts
Labels: bug

#172 Fixed Sidebar bug
  frontend/components/AccountManage.vue
  frontend/pages/Login/index.vue
  frontend/pages/confirm/index.vue
Labels: testing

#181 Fixed padding issues with layout
  frontend/components/FieldCard.vue
  frontend/components/GoogleMap.vue
  frontend/components/GoogleMapsField.vue
  frontend/components/LogsView.vue
  frontend/components/StatsCard.vue
  frontend/layouts/default.vue
  frontend/pages/Login/index.vue
  frontend/pages/index.vue
  frontend/pages/inputs/manage-fields/index.vue
  frontend/pages/settings/index.vue
  frontend/presets/lara/panel/index.js
  frontend/presets/lara/tag/index.js
Labels: enhancement, frontend
